baseURL = "https://michaelhealy.space/designing-writing/"
languageCode = "en-us"
title = "Designing Writing"
publishDir = "docs"
theme = "hyde-hyde"
canonifyURLs = true

## Site Settings
[params]
    author = "All of Us"
    title = "Context Matters"
    themeColor = "theme-base-0d"
    # description = "..."
    authorimage = "/img/hugo.png"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    # highlightjsstyle = "github"
    # please choose either GraphComment or Disqus
    # GraphCommentId = "your-graph-comment-id"

## Social Accounts
[params.social]
    github = "<username>"
    instagram = "<username>"
    xing = "<username>"
    linkedin = "<username>"
    twitter = "<username>"
    facebook = "<username>"
    stackoverflow = "<username>"
    email = "your-email@example.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"
